[[main]]
    name = "À propos"
    weight = 10
    pageRef = '/about'
[[main]]
    parent = "À propos"
    name = "À propos de l'IRSD"
    weight = 11
    pageRef = '/about'
[[main]]
    parent = "À propos"
    name = "Services"
    weight = 12
    pageRef = '/services'
# [[main]]
#     name = "Actualités"
#     weight = 20
#     pageRef = '/posts'
[[main]]
    name = "Équipes"
    weight = 30
    pageRef = '/equipes'
[[main]]
    parent = "Équipes"
    name = "Vergnolle/Deraison - Gut Protease Signals"
    weight = 31
    pageRef = '/eq1'
[[main]]
    parent = "Équipes"
    name = "Oswald - Pathogénie et commensalisme des entérobactéries"
    weight = 32
    pageRef = '/eq2'
[[main]]
    parent = "Équipes"
    name = "Djebali/Monlong - Bioinformatics Research In Disease Genomics (BRIDGe)"
    weight = 34
    pageRef = '/eq4'
[[main]]
    parent = "Équipes"
    name = "Kautz - Erythroferrone et Homéostasie Martiale"
    weight = 35
    pageRef = '/eq5'
[[main]]
    parent = "Équipes"
    name = "Barreau - Environnement et épithélium intestinal"
    weight = 36
    pageRef = '/eq6'
[[main]]
    parent = "Équipes"
    name = "Vaubourgeix - Systems Biology of Bacterial Antibiotic Resistance Mechanisms"
    weight = 37
    pageRef = '/eqjv'
[[main]]
    name = "Plateformes"
    weight = 40
    pageRef = "/platforms"
[[main]]
    parent = "Plateformes"
    name = "Plateforme Plateforme Modèles Digestifs"
    weight = 41
    pageRef = '/platform-digestive'
[[main]]
    parent = "Plateformes"
    name = "Plateforme Organoïdes"
    weight = 42
    pageRef = '/platform-organoid'
[[main]]
    parent = "Plateformes"
    name = "Plateforme Bio-Ingenierie des Proteines"
    weight = 43
    pageRef = '/platform-bip'
[[main]]
    name = "Personnel"
    weight = 50
    pageRef = '/people'
[[main]]
    name = "Publications"
    weight = 60
    pageRef = '/publications'
[[main]]
    name = "Contacts"
    weight = 70
    pageRef = '/contact'
